---
- name: Configure Ubuntu as a load balancer with Nginx
  hosts: loadbalancer
  become: true
  tasks:
    - name: Ensure Nginx is installed
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
        
    - name: Upload loadbalancer config
      ansible.builtin.template:
        src: loadbalancer.tpl 
        dest: /etc/nginx/sites-available/default
        mode: 0755
      notify: restart nginx

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx 
        state: restarted
        enabled: yes
