---
- name: Deploy Docker Compose on remote host
  hosts: remote
  become: true
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker Compose is installed
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create application directory
      file:
        path: /opt/app
        state: directory

    - name: Copy Docker Compose file to remote host
      copy:
        src: ../database/docker-compose.yml
        dest: /opt/app/docker-compose.yml

    - name: Start Docker Compose application
      command: docker-compose up -d
      args:
        chdir: /opt/app
