---
servers:
  hosts:
    loadbalancer:
      ansible_host: 18.197.13.79
      ansible_connection: ssh
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ../my-key.pem
    frontend:
      ansible_host: 192.168.1.51
      ansible_connection: ssh
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ../my-key.pem
      ansible_ssh_common_args: '-o ProxyCommand="ssh -i ../my-key.pem ubuntu@18.197.13.79 nc %h 22"'
    backend:
      ansible_host: 192.168.0.12
      ansible_connection: ssh
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ../my-key.pem
      ansible_ssh_common_args: '-o ProxyCommand="ssh -i ../my-key.pem ubuntu@18.197.13.79 nc %h 22"'
    postgres:
      ansible_host: 192.168.3.30
      ansible_connection: ssh
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ../my-key.pem
      ansible_ssh_common_args: '-o ProxyCommand="ssh -i ../my-key.pem ubuntu@18.197.13.79 nc %h 22"'