---
servers:
  hosts:
    server1:
      ansible_host:
      ansible_connection:
      ansible_ssh_user:
      ansible_ssh_private_key_file:
    server2:
      ansible_host:
      ansible_connection:
      ansible_ssh_user:
      ansible_ssh_private_key_file:
    server3:
      ansible_host:
      ansible_connection:
      ansible_ssh_user:
      ansible_ssh_private_key_file: