---
load_balancer:
  hosts:
    reverse-proxy:
      ansible_host:
      ansible_user: ubuntu
      ansible_ssh_user: ubuntu
      ansible_connection: ssh
      ansible_ssh_private_key_file: name-of-ssh-key.pem

webservers:
  hosts:
    frontend:
      ansible_host:
      ansible_user: ubuntu
      ansible_ssh_user: ubuntu
      ansible_connection: ssh
      ansible_ssh_private_key_file: name-of-ssh-key.pem

    backend:
      ansible_host:
      ansible_user: ubuntu
      ansible_ssh_user: ubuntu
      ansible_connection: ssh
      ansible_ssh_private_key_file: name-of-ssh-key.pem

databases:
  hosts:
    postgresql:
      ansible_host:
      ansible_user: ubuntu
      ansible_ssh_user: ubuntu
      ansible_connection: ssh
      ansible_ssh_private_key_file: name-of-ssh-key.pem