---
- name: Install Docker
  hosts: webservers
  become: true
  tasks:
    -
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create directory for apt keyrings
      ansible.builtin.command: "install -m 0755 -d /etc/apt/keyrings"
      become: true

    - name: Download Docker's official GPG key
      ansible.builtin.command: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc"
      become: true

    - name: Change the access to the GPG key
      ansible.builtin.command: "chmod a+r /etc/apt/keyrings/docker.asc"
      become: true

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted